from . import help
from . import start
from . import adres
from . import qoshtepa
from . import toshloq
from . import admin_start
from . import ariza_qoldirish
from . import admin_kommands
from . import echo